version: '2'
services:
    final-mysql:
        container_name: final-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/Final/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_DATABASE=final
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
